[buildPlans.IosevkaBasedCursive]
family = "Iosevka Based Cursive"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaBasedCursive.variants.design]
one = "no-base"
two = "curly-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
five = "upright-flat-serifless"
six = "straight-bar"
seven = "straight-serifless-crossbar"
eight = "two-circles"
nine = "straight-bar"
zero = "dotted"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-tailed"
b = "toothed-serifless"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "double-storey-open"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck"
u = "tailed-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
punctuation-dot = "square"
tilde = "low"
asterisk = "penta-mid"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "open"
cent = "open-cap"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "smooth"

[buildPlans.IosevkaBasedCursive.variants.italic]
one = "no-base"
two = "curly-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
five = "upright-flat-serifless"
six = "straight-bar"
seven = "straight-serifless-crossbar"
eight = "two-circles"
nine = "straight-bar"
zero = "dotted"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "single-storey-double-serifed"
b = "toothed-serifless"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "serifed-semi-tailed"
j = "flat-hook-serifed"
k = "cursive-serifless"
l = "serifed-semi-tailed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-short-neck"
u = "tailed-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
punctuation-dot = "square"
tilde = "low"
asterisk = "penta-mid"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "closed"
at = "fourfold"
dollar = "open"
cent = "open-cap"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "smooth"

[buildPlans.IosevkaBasedCursive.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaBasedCursive.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaBasedCursive.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaBasedCursive.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaBasedCursive.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaBasedCursive.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaBasedCursive.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaBasedCursive.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaBasedCursive.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaBasedCursive.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaBasedCursive.metricOverride]
leading = 1700
sb = 83
xHeight = 520
cap = 690
ascender = 740
parenSize = 970

accentWidth = 182
accentClearance = 76
accentHeight = 162
accentStackOffset = 208

essRatio = 1.03
essRatioUpper = 1.03
essRatioLower = 1.03
essRatioQuestion = 1.03
archDepth = 152
smallArchDepth = 157
